name: React Build, Test, and Release

on:
  push:
    branches:
      - main
      - 05-firefox-support
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run React Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18] # Test with multiple Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build React App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('src/**/*', 'public/**/*', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Default React App
        run: npm run build

      - name: Build React App for Firefox
        run: npm run build-firefox

      - name: Build React App for Firefox
        run: npm run build-chrome

      # Upload Build artifact for default config.
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookmark_extension_v2_default
          path: build/default
      # Upload Build artifact for Chrome browsers.
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookmark_extension_v2_chrome
          path: build/chrome
      # Upload Build artifact for Firefox browsers.
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookmark_extension_v2_firefox
          path: build/firefox
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: read
    steps:
      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: bookmark_extension_v2_chrome
      # To Debug folder structure.
      - name: Display structure of downloaded files
        run: ls -R
      # Zip up the files.
      - name: Zip Build Folder
        run: |
          zip -r bookmark_extension_v2_chrome.zip . -i build
      # Create Github Release
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: "Automated Release v${{ github.run_number }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Upload Build for release.
      - name: Upload Build to Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: react-build.zip
          asset_name: react-build.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Delete Artifact to reduce space usage
      - name: Delete Artifact from build
        uses: geekyeggo/delete-artifact@v5
        with:
          name: react-build
